version: '3.3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Ayouda123
      MYSQL_DATABASE: gestionexpertise
      MYSQL_USER: mokhtar
      MYSQL_PASSWORD: Ayouda123
    ports:
      - "3308:3306"  # Port MySQL sur l'hôte

  gestionexpertise-backend:
    image: mokhtar2000/gestionexpertise:latest  # Ton image DockerHub
    ports:
      - "8089:8080"  # Port de l'application Spring Boot
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestionexpertise?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: mokhtar
      SPRING_DATASOURCE_PASSWORD: Ayouda123
      SPRING_SERVER_PORT: 8080
